indexAlise = 'index（词目序号）'
glossAlise = 'combine（词目）'
isCorrectAlise = 'IsCorrect（值0，1，2，3）'
patterAlise_L_1 = 'L_handshape_1'
fadeInAlise_L_1 = 'L_fade_in_F_1'
startAlise_L_1 = 'L_start_F_1'
endAlise_L_1 = 'L_end_F_1'
fadeOutAlise_L_1 = 'L_fade_out_1'

patterAlise_L_2 = 'L_handshape_2'
fadeInAlise_L_2 = 'L_fade_in_F_2'
startAlise_L_2 = 'L_start_F_2'
endAlise_L_2 = 'L_end_F_2'
fadeOutAlise_L_2 = 'L_fade_out_2'

patterAlise_L_3 = 'L_handshape_3'
fadeInAlise_L_3 = 'L_fade_in_F_3'
startAlise_L_3 = 'L_start_F_3'
endAlise_L_3 = 'L_end_F_3'
fadeOutAlise_L_3 = 'L_fade_out_3'

patterAlise_L_4 = 'L_handshape_4'
fadeInAlise_L_4 = 'L_fade_in_F_4'
startAlise_L_4 = 'L_start_F_4'
endAlise_L_4 = 'L_end_F_4'
fadeOutAlise_L_4 = 'L_fade_out_4'

patterAlise_R_1 = 'R_handshape_1'
fadeInAlise_R_1 = 'R_fade_in_F_1'
startAlise_R_1 = 'R_start_F_1'
endAlise_R_1 = 'R_end_F_1'
fadeOutAlise_R_1 = 'R_fade_out_1'

patterAlise_R_2 = 'R_handshape_2'
fadeInAlise_R_2 = 'R_fade_in_F_2'
startAlise_R_2 = 'R_start_F_2'
endAlise_R_2 = 'R_end_F_2'
fadeOutAlise_R_2 = 'R_fade_out_2'

patterAlise_R_3 = 'R_handshape_3'
fadeInAlise_R_3 = 'R_fade_in_F_3'
startAlise_R_3 = 'R_start_F_3'
endAlise_R_3 = 'R_end_F_3'
fadeOutAlise_R_3 = 'R_fade_out_3'

patterAlise_R_4 = 'R_handshape_4'
fadeInAlise_R_4 = 'R_fade_in_F_4'
startAlise_R_4 = 'R_start_F_4'
endAlise_R_4 = 'R_end_F_4'
fadeOutAlise_R_4 = 'R_fade_out_4'
