# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_check.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_proof(object):
    def setupUi(self, Dialog_proof):
        Dialog_proof.setObjectName("Dialog_proof")
        Dialog_proof.resize(577, 405)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog_proof.setFont(font)
        self.pushButton_proof_yes = QtWidgets.QPushButton(Dialog_proof)
        self.pushButton_proof_yes.setGeometry(QtCore.QRect(220, 330, 141, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_proof_yes.setFont(font)
        self.pushButton_proof_yes.setObjectName("pushButton_proof_yes")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog_proof)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 20, 481, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_res_4 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_res_4.setFont(font)
        self.radioButton_res_4.setAutoExclusive(False)
        self.radioButton_res_4.setObjectName("radioButton_res_4")
        self.gridLayout.addWidget(self.radioButton_res_4, 3, 0, 1, 1)
        self.radioButton_res_0 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_res_0.setFont(font)
        self.radioButton_res_0.setAutoExclusive(False)
        self.radioButton_res_0.setObjectName("radioButton_res_0")
        self.gridLayout.addWidget(self.radioButton_res_0, 0, 0, 1, 1)
        self.radioButton_res_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_res_2.setFont(font)
        self.radioButton_res_2.setAutoExclusive(False)
        self.radioButton_res_2.setObjectName("radioButton_res_2")
        self.gridLayout.addWidget(self.radioButton_res_2, 1, 0, 1, 1)
        self.radioButton_res_1 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_res_1.setFont(font)
        self.radioButton_res_1.setAutoExclusive(False)
        self.radioButton_res_1.setObjectName("radioButton_res_1")
        self.gridLayout.addWidget(self.radioButton_res_1, 0, 1, 1, 1)
        self.radioButton_res_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_res_3.setFont(font)
        self.radioButton_res_3.setAutoExclusive(False)
        self.radioButton_res_3.setObjectName("radioButton_res_3")
        self.gridLayout.addWidget(self.radioButton_res_3, 1, 1, 1, 1)
        self.textEdit_proof = QtWidgets.QTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_proof.sizePolicy().hasHeightForWidth())
        self.textEdit_proof.setSizePolicy(sizePolicy)
        self.textEdit_proof.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_proof.setObjectName("textEdit_proof")
        self.gridLayout.addWidget(self.textEdit_proof, 3, 1, 1, 1)

        self.retranslateUi(Dialog_proof)
        QtCore.QMetaObject.connectSlotsByName(Dialog_proof)

    def retranslateUi(self, Dialog_proof):
        _translate = QtCore.QCoreApplication.translate
        Dialog_proof.setWindowTitle(_translate("Dialog_proof", "视频评估"))
        self.pushButton_proof_yes.setText(_translate("Dialog_proof", "确认"))
        self.radioButton_res_4.setText(_translate("Dialog_proof", "其他（请补充）"))
        self.radioButton_res_0.setText(_translate("Dialog_proof", "无问题"))
        self.radioButton_res_2.setText(_translate("Dialog_proof", "表演问题"))
        self.radioButton_res_1.setText(_translate("Dialog_proof", "手形问题"))
        self.radioButton_res_3.setText(_translate("Dialog_proof", "空间问题"))
