# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_hint.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_hint(object):
    def setupUi(self, Dialog_hint):
        Dialog_hint.setObjectName("Dialog_hint")
        Dialog_hint.resize(644, 419)
        self.textEdit_hint = QtWidgets.QTextEdit(Dialog_hint)
        self.textEdit_hint.setGeometry(QtCore.QRect(40, 40, 561, 301))
        self.textEdit_hint.setObjectName("textEdit_hint")
        self.pushButton_back = QtWidgets.QPushButton(Dialog_hint)
        self.pushButton_back.setGeometry(QtCore.QRect(460, 360, 141, 34))
        self.pushButton_back.setObjectName("pushButton_back")

        self.retranslateUi(Dialog_hint)
        QtCore.QMetaObject.connectSlotsByName(Dialog_hint)

    def retranslateUi(self, Dialog_hint):
        _translate = QtCore.QCoreApplication.translate
        Dialog_hint.setWindowTitle(_translate("Dialog_hint", "提示"))
        self.pushButton_back.setText(_translate("Dialog_hint", "返回"))
